name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  ubuntu_14:
    name: ubuntu_14
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:14.04
      volumes:
        - /node20217:/node20217:rw,rshared
        - /node20217:/__e/node20:ro,rshared
    steps:
    - name: nodejs
      run: |
        apt-get update && apt-get install -y wget xz-utils
        wget https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-linux-x64-glibc-217.tar.xz
        tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev gcc g++ autoconf automake make
    - name: env
      run: lsb_release -a &&  ldd --version && gcc --version && g++ --version
    - name: build
      run:  make -j8
    - name: test
      run: make test
  ubuntu_16:
    name: Ubuntu 16
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:16.04
      volumes:
        - /node20217:/node20217:rw,rshared
        - /node20217:/__e/node20:ro,rshared
    steps:
    - name: nodejs
      run: |
        apt-get update && apt-get install -y wget xz-utils
        wget https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-linux-x64-glibc-217.tar.xz
        tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
    - uses: actions/checkout@v2
    - name: install packages
      run: apt-get update && apt-get install -y zlib1g-dev gcc g++ autoconf automake make
    - name: build
      run: make -j8
    - name: test
      run: make test
  ubuntu_16_cmake:
    name: Ubuntu 16 cmake
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:16.04
      volumes:
        - /node20217:/node20217:rw,rshared
        - /node20217:/__e/node20:ro,rshared
    steps:
    - name: nodejs
      run: |
        apt-get update && apt-get install -y wget xz-utils
        wget https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-linux-x64-glibc-217.tar.xz
        tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
    - uses: actions/checkout@v2
    - name: install packages
      run: apt-get update && apt-get install -y zlib1g-dev gcc g++ autoconf automake make cmake
    - name: build
      run:  mkdir build && cd build && cmake -DSLOW5_LINK_STATIC=ON -DSLOW5_USE_ZSTD=OFF -DSLOW5_ENABLE_MT=OFF .. && make -j8
  ubuntu_18:
    name: Ubuntu 18
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:18.04
      volumes:
        - /node20217:/node20217:rw,rshared
        - /node20217:/__e/node20:ro,rshared
    steps:
    - name: nodejs
      run: |
        apt-get update && apt-get install -y wget xz-utils
        wget https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-linux-x64-glibc-217.tar.xz
        tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
    - uses: actions/checkout@v2
    - name: install packages
      run:  apt-get update && apt-get install -y zlib1g-dev valgrind gcc g++ autoconf automake make
    - name: build
      run:  make -j8
    - name: test
      run: make test
    - name: test valgrind
      run: ./test/test.sh mem
    - name: examples
      run: make examples
  ubuntu_20:
    name: Ubuntu 20
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:20.04
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: apt-get update && apt-get install -y zlib1g-dev gcc g++ autoconf automake make clang
    - name: build-gcc
      run: make -j8
    - name: test-gcc
      run: make test
    - name: build-clang
      run: make clean && make CC=clang -j8
    - name: test-clang
      run: make test
  ubuntu_22:
    name: Ubuntu 22
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get update && sudo apt-get install zlib1g-dev
    - name: build-gcc
      run: make -j8
    - name: test-gcc
      run: make test
  ubuntu_24:
    name: Ubuntu 24
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get update && sudo apt-get install zlib1g-dev
    - name: build-gcc
      run: make -j8
    - name: test-gcc
      run: make test

  # os_x_13:
  #   name: OSX 13
  #   runs-on: macos-13
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: build
  #     run: make -j8
  #   - name: test
  #     run: make test
  #   - name: examples
  #     run: make examples
  # os_x_14:
  #   name: OSX 14
  #   runs-on: macos-14
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: build
  #     run: make -j8
  #   - name: test
  #     run: make test
  #   - name: examples
  #     run: make examples
  # arm64:
  #   name: ubuntu arm
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
  #   - uses: docker://multiarch/ubuntu-core:arm64-bionic
  #     with:
  #       args: 'uname -a'
  #   - uses: actions/checkout@v1
  #   - uses: docker://multiarch/ubuntu-core:arm64-bionic
  #     with:
  #       args: >
  #         bash -c "apt-get update &&
  #         apt-get install -y zlib1g-dev gcc make &&
  #         ldd --version && gcc --version &&
  #         make && make test"
